#!/bin/bash

set -ex

export ROOT_DIR="${PWD}"
export PREFIX="${ROOT_DIR}/install/"
export CXXFLAGS="-I${PREFIX}/include -g4" CFLAGS="-I${PREFIX}/include -g4" LDFLAGS="-L${PREFIX}/lib"

mkdir -p sources
pushd sources

aria2c --check-integrity=true --input-file=<(cat <<EOF
https://github.com/emscripten-core/emsdk/archive/2.0.4.tar.gz
    out=emsdk.tar.gz
    checksum=sha-256=55e2b4bd5a45fa5cba21eac4deaebda061edd4a2b8f753ffbce3f51eb19512da
https://github.com/Qalculate/libqalculate/releases/download/v3.13.0/libqalculate-3.13.0.tar.gz
    out=libqalculate.tar.gz
    checksum=sha-256=329700f6ee9f634e5383598197efe94861cd49ce1d9b40b61558fa578d58de1c
https://gmplib.org/download/gmp/gmp-6.2.0.tar.xz
    out=gmp.tar.xz
    checksum=sha-256=258e6cd51b3fbdfc185c716d55f82c08aff57df0c6fbd143cf6ed561267a1526
https://www.mpfr.org/mpfr-current/mpfr-4.1.0.tar.xz
    out=mpfr.tar.xz
    checksum=sha-256=0c98a3f1732ff6ca4ea690552079da9c597872d30e96ec28414ee23c95558a7f
ftp://xmlsoft.org/libxml2/libxml2-2.9.10.tar.gz
    out=libxml2.tar.gz
    checksum=sha-256=aafee193ffb8fe0c82d4afef6ef91972cbaf5feea100edc2f262750611b4be1f
EOF
)

if [ ! -e emsdk ]; then
    tar xf emsdk.tar.gz
    mv emsdk-* emsdk
fi
if [ ! -e gmp ]; then
    tar xf gmp.tar.xz
    mv gmp-* gmp
fi
if [ ! -e libqalculate ]; then
    tar xf libqalculate.tar.gz
    mv libqalculate-* libqalculate
fi
if [ ! -e mpfr ]; then
    tar xf mpfr.tar.xz
    mv mpfr-* mpfr
fi
if [ ! -e libxml2 ]; then
    tar xf libxml2.tar.gz
    mv libxml2-* libxml2
fi

pushd emsdk
    ./emsdk install 2.0.4
    ./emsdk activate 2.0.4

    source "${PWD}/emsdk_env.sh"
popd

pushd libxml2
    emconfigure ./configure --host none --prefix="${PREFIX}" --without-c14n --without-catalog --without-debug --without-docbook --without-ftp --without-html --without-http --without-iconv --without-iso8859x --without-legacy --without-pattern --without-push --without-python --without-reader --without-regexps --without-schemas --without-schematron --without-threads --without-valid --without-writer --without-xinclude --without-xpath --without-xptr --without-modules
    make -j "$(nproc)" install
popd

pushd gmp
    emconfigure ./configure --disable-assembly --host none --enable-cxx --prefix="${PREFIX}"
    make -j "$(nproc)" install
popd

pushd mpfr
    emconfigure ./configure --host none --prefix="${PREFIX}"
    make -j "$(nproc)" install
popd

pushd libqalculate
    patch -p1 --forward < ../../libqalculate-popen.patch
    LIBXML_CFLAGS="-I${PREFIX}/include/libxml2" LIBXML_LIBS="${LDFLAGS}" emconfigure ./configure --host none --prefix="${PREFIX}" --without-libcurl --without-icu --disable-textport --disable-nls
    make -j "$(nproc)" install
popd

popd

mkdir -p build
pushd build

export EMMAKEN_CFLAGS="$CFLAGS $LDFLAGS"
emcc -s DEMANGLE_SUPPORT=1 -s SAFE_HEAP=1 -s WARN_UNALIGNED=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -llibqalculate -lgmp -lmpfr -lxml2 ../test.cpp -o test.html --source-map-base http://localhost:8000/

python -m http.server 8000
